/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import static Controleur.ConnectionDB.ConnecterDB;
import java.sql.SQLException;
import javax.swing.JFrame;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author morga
 */
public class FenetreInscription extends javax.swing.JFrame {

    /**
     * Creates new form FenetreInscription
     */
    public FenetreInscription() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        //bouton btnValider
        if (textMdp.getText() != null && textPseudo.getText() != null) {
            BtnValider.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    //update base de données
                    /*Connection conn = ConnecterDB();
                    Statement state;
                    try {
                        state = conn.createStatement();
                        int insert = state.executeUpdate("INSERT INTO JOUEUR VALUES((Select id from Joueur where id max)+1, textPseudo.getText(), textMdp.getText());");
                        state.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(FenetrePerso.class.getName()).log(Level.SEVERE, null, ex);
                        System.out.println("Exeption soulevé par la base de données");
                    }*/
                    FenetrePerso f = new FenetrePerso();
                    f.setVisible(true);
                    dispose();

                }

            });
        }
        //bouton retour
        BtnAnnuler.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                FenetreIntro f = new FenetreIntro();
                f.setVisible(true);
                dispose();
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPseudo = new javax.swing.JLabel();
        textPseudo = new javax.swing.JTextField();
        labelMdp = new javax.swing.JLabel();
        textMdp = new javax.swing.JTextField();
        BtnValider = new javax.swing.JButton();
        BtnAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        labelPseudo.setFont(new java.awt.Font("Balthazar", 0, 11)); // NOI18N
        labelPseudo.setText("Pseudo : ");

        labelMdp.setFont(new java.awt.Font("Balthazar", 0, 11)); // NOI18N
        labelMdp.setText("Mot de passe :");

        BtnValider.setFont(new java.awt.Font("Balthazar", 0, 11)); // NOI18N
        BtnValider.setText("Valider");
        BtnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnValiderActionPerformed(evt);
            }
        });

        BtnAnnuler.setFont(new java.awt.Font("Balthazar", 0, 11)); // NOI18N
        BtnAnnuler.setText("Annuler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPseudo)
                            .addComponent(labelMdp))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textPseudo)
                            .addComponent(textMdp, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(BtnValider)
                        .addGap(88, 88, 88)
                        .addComponent(BtnAnnuler)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPseudo)
                    .addComponent(textPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMdp)
                    .addComponent(textMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnValider)
                    .addComponent(BtnAnnuler))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnValiderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnValiderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreInscription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnnuler;
    private javax.swing.JButton BtnValider;
    private javax.swing.JLabel labelMdp;
    private javax.swing.JLabel labelPseudo;
    private javax.swing.JTextField textMdp;
    private javax.swing.JTextField textPseudo;
    // End of variables declaration//GEN-END:variables
}
