/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;
import Controleur.Message;
import Controleur.Observateur;
import Modele.EnigmeChampsDeTexte;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
/**
 *
 * @author Léa
 */
public class PanelEnigmeCDT extends javax.swing.JPanel {

    /**
     * Creates new form PanelEnigmeCDT
     */
    private Observateur observateur;
    
    public PanelEnigmeCDT(EnigmeChampsDeTexte e, int largeur, int hauteur) {
        initComponents();
        this.setSize(largeur, hauteur);
        question.setText(e.getQuestion());
        valider.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Message m = new Message();
                m.setEtat("MessageChampsDeTexte");
                m.setAtt1(reponse.getText());
                observateur.notification(m);
            }
            
        });
        boutonRetour();
    }
    
    public void setObservateur(Observateur observateur) {
        this.observateur = observateur;
    }
    
    public void boutonRetour() {
        //met en place tous les boutons sur le Jpanel
        JButton retour = new JButton("retour");
        //taille par défault du bouton
        retour.setSize(70, 70);
        //localisation par défaut du bouton
        retour.setLocation(0, 0);
        //action listener pour retourner "retour" a l'appuye du bouton
        retour.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Message m = new Message();
                //renvoyer le nom du bouton pas le texte
                m.setEtat("retour");
                observateur.notification(m);
            }
        }
        );
        //ajouter une image pour le bouton retour!!!
        this.add(retour);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valider = new javax.swing.JButton();
        reponse = new javax.swing.JTextField();
        question = new javax.swing.JLabel();

        setLayout(null);

        valider.setText("Valider");
        add(valider);
        valider.setBounds(167, 118, 74, 26);

        reponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reponseActionPerformed(evt);
            }
        });
        add(reponse);
        reponse.setBounds(126, 80, 159, 20);

        question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        question.setText("---");
        add(question);
        question.setBounds(0, 46, 388, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void reponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reponseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel question;
    private javax.swing.JTextField reponse;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
