/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Controleur.Message;
import Controleur.Observateur;
import Modele.EnigmeChampsDeTexte;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Léa
 */
public class PanelEnigmeChampsDeTexte extends javax.swing.JPanel {

    /**
     * Creates new form PanelEnigmeChampsDeTexte
     */
        private Observateur observateur;

    public PanelEnigmeChampsDeTexte(EnigmeChampsDeTexte e, int largeur, int hauteur) {
        initComponents();
        this.setSize(largeur, hauteur);
        question.setText(e.getQuestion());
        valider.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Message m = new Message();
                m.setAtt1(reponse.getText());
                observateur.notification(m);
            }
            
        });
    }
    
    public void setObservateur(Observateur observateur) {
        this.observateur = observateur;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        question = new javax.swing.JLabel();
        reponse = new javax.swing.JTextField();
        valider = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        question.setText("-----");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 202;
        gridBagConstraints.ipady = 56;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(question, gridBagConstraints);

        reponse.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        reponse.setText("...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 174;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(reponse, gridBagConstraints);

        valider.setText("Valider");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        add(valider, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel question;
    private javax.swing.JTextField reponse;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
