/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author Léa
 */
public class PanelJeu extends javax.swing.JPanel {

    private ArrayList<JButton> mondes;
    /**
     * Creates new form PanelJeu
     */
    public PanelJeu(int nbMondes) {
        initComponents();
        mondes=new ArrayList<JButton>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public void addMondes(int nbMondes){
        //Methodes pour ajouter le nobre de mondes(mondes = boutons)
        int largeur = this.getWidth();
        int hauteur = this.getHeight()/2;
        int posiInit= largeur/(nbMondes+1);
        int i,posiObj;
        posiObj=posiInit;
        for(i=0;1<nbMondes;i++){
            JButton bouton = new JButton();
            bouton.setLocation(posiObj, hauteur);
            this.add(bouton);
            mondes.add(bouton);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
